### ISSUE TITLE
Error During Git Checkout with Invalid Path Names Containing Special Characters

### ISSUE THREAD

**Issue by Vishwabhadiyadara** [aditya-prayaga/FinSight#3]
**Issue Description:**
When attempting to clone and check out a repository, the process fails during the checkout phase due to an invalid path error. This appears to be caused by path names containing special characters like equal signs (=) and colons (:), which are not compatible with all file systems.

**Steps to Reproduce:**
Clone the repository containing the problematic path names.
Attempt to checkout the repository.
Expected Behavior
The repository should be cloned and checked out without any errors, regardless of the file system.

**Expected Behavior:**
The repository should be cloned and checked out without any errors, regardless of the file system.

**Actual Behavior:**
The checkout process fails with the following error:

```
error: invalid path 'logs/dag_id=FinSight_pipeline/run_id=manual__2024-06-09T02:43:01.674113+00:00/task_id=download_upload_data/attempt=1.log'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Possible Solutions:**
Rename Files: 
Avoid using special characters such as =, :, and spaces in file names and directories.
Use Git Config: Modify the git configuration to handle special characters if renaming is not feasible:
bash
Copy code
`git config --global core.protectNTFS false`

**Additional Information:**
Operating System: (include your OS here, e.g., Windows 10)
Git Version: (include your Git version here, e.g., 2.24.1)

**Tags:**
'bug' 'git' 'checkout' 'file-system'

**Comment by aditya-prayaga** [comment]
Remove the file in the log so that git doesn't track it, and it would work fine.
